#!/bin/bash
# postrm script for sit

if [ -d /etc/apache2/conf.d ] && [ ! -e /etc/apache2/conf.d/sit.conf ]; then
    rm /etc/apache2/conf.d/sit.conf
fi

if [ -x /usr/sbin/invoke-rc.d ]; then
    /usr/sbin/invoke-rc.d apache2 reload
else
    /etc/init.d/apache2 reload
fi