#!/bin/bash
# Postint script for SiT

# Add the sit include to the include_path

if [ -e /etc/php5/apache2/php.ini ]; then
    cp /etc/php5/apache2/php.ini /etc/php5/apache2/php.ini.presit
    newinc=`cat /etc/php5/apache2/php.ini|awk '/^include_path/{print $3}'|sed 's/"$/\:\/usr\/share\/sit\/includes\/"/g'`
    newinc1=`echo $newinc|sed 's/\\//\\\\\\//g'`
    sed -i 's/^include_path.*$/include_path = '$newinc1'/' /etc/php5/apache2/php.ini
fi

if [ -e /etc/php4/apache2/php.ini ]; then
    cp /etc/php4/apache2/php.ini /etc/php4/apache2/php.ini.presit
    newinc=`cat /etc/php5/apache2/php.ini|awk '/^include_path/{print $3}'|sed 's/"$/\:\/usr\/share\/sit\/includes\/"/g'`
    newinc1=`echo $newinc|sed 's/\\//\\\\\\//g'`
    sed -i 's/^include_path.*$/include_path = '$newinc1'/' /etc/php4/apache2/php.ini
fi

if [ -d /etc/apache2/conf.d ] && [ ! -e /etc/apache2/conf.d/sit.conf ]; then
    ln -s /etc/sit/apache.conf /etc/apache2/conf.d/sit.conf
fi

if [ -x /usr/sbin/invoke-rc.d ]; then
    /usr/sbin/invoke-rc.d apache2 reload
else
    /etc/init.d/apache2 reload
fi

