#!/bin/sh -e
# Postint script for SiT

if [ -d /etc/apache2/conf.d ] && [ ! -e /etc/apache2/conf.d/sit.conf ]; then
    ln -s /etc/sit/apache.conf /etc/apache2/conf.d/sit.conf
fi

if [ -x /usr/sbin/invoke-rc.d ]; then
    invoke-rc.d apache2 reload
else
    /etc/init.d/apache2 reload
fi

chgrp www-data /etc/sit.conf
chmod 660 /etc/sit.conf

chgrp -R www-data /usr/share/sit
chmod 660 /usr/share/sit/attachments

ln -s /usr/share/javascript/prototype/prototype.js /usr/share/sit/scripts/prototype/prototype.js
ln -s /usr/share/javascript/scriptalicious/scriptalicious.js /usr/share/sit/scripts/scriptalicious.js

#DEBHELPER#
