#!/bin/sh -e
# postrm script for sit

if [ -d /etc/apache2/conf.d ] && [ ! -e /etc/apache2/conf.d/sit.conf ]; then
    rm /etc/apache2/conf.d/sit.conf
fi

if [ -x /usr/sbin/invoke-rc.d ]; then
	invoke-rc.d apache2 restart
else
	/etc/init.d/apache2 restart
fi

#DEBHELPER#
